### ISSUE TITLE
When executing the cartographer_offline_node executable it crashes

### ISSUE THREAD

**Issue by Shubhranshu153** [ojura/cartographer_superbuild#4]
F0918 15:03:33.563668  9225 offline_node.cc:80] Check failed: !FLAGS_configuration_directory.empty() -configuration_directory is missing.
F0918 15:03:33.000000  9225 offline_node.cc:80] Check failed: !FLAGS_configuration_directory.empty() -configuration_directory is missing.
*** Check failure stack trace: ***
    @     0x7fa18c1ef0cd  google::LogMessage::Fail()
    @     0x7fa18c1f0f33  google::LogMessage::SendToLog()
    @     0x7fa18c1eec28  google::LogMessage::Flush()
    @     0x7fa18c1f1999  google::LogMessageFatal::~LogMessageFatal()
    @     0x558d2b70e1e8  (unknown)
    @     0x558d2b70655a  (unknown)
    @     0x7fa189e18b97  __libc_start_main
    @     0x558d2b70b4ea  (unknown)
Aborted (core dumped)

May be i am doing the execution wrong?

**Comment by yuan608** [comment]
I guess you may have not added configuration_directory in cartographer_offline_node. I met the same issue at cartographer_node, and I resolved it successfully by add configuration_directory in node_main,cc. Maybe you can do the same thing at offline_node.cc.
![Screenshot from 2020-10-15 15-58-49](https://user-images.githubusercontent.com/70429489/96093977-60e4f880-0eff-11eb-877f-75058d94d222.png)

**Comment by ojura** [comment]
This argument should be provided in the command line. The error message itself is telling you what to do, ie. add the ` -configuration_directory` command line argument.
