### ISSUE TITLE
"base_link" passed to lookupTransform argument target_frame does not exist

### ISSUE THREAD

**Issue by yuan608** [ojura/cartographer_superbuild#5]
Hi，
     I was trying to debug the code in CLion. However, it gives me a lot of warning messages: 

[ INFO] [1602409271.778359122]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer_ros/cartographer_ros/configuration_files/backpack_2d.lua' for 'backpack_2d.lua'.
[ INFO] [1602409271.778863151]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1602409271.778906037]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/map_builder.lua' for 'map_builder.lua'.
[ INFO] [1602409271.778939008]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[ INFO] [1602409271.778956540]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/pose_graph.lua' for 'pose_graph.lua'.
[ INFO] [1602409271.779041807]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[ INFO] [1602409271.779093004]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder.lua' for 'trajectory_builder.lua'.
[ INFO] [1602409271.779124441]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1602409271.779141409]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder_2d.lua' for 'trajectory_builder_2d.lua'.
[ INFO] [1602409271.779223140]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1602409271.779278916]: I1011 17:41:11.000000 31371 configuration_file_resolver.cc:41] Found '/home/yuan/test3/cartographer_superbuild/cartographer/configuration_files/trajectory_builder_3d.lua' for 'trajectory_builder_3d.lua'.
[ INFO] [1602409271.783340706]: I1011 17:41:11.000000 31371 map_builder_bridge.cc:136] Added trajectory with ID '0'.
[ WARN] [1602409274.787163816]: W1011 17:41:14.000000 31371 node.cc:857] Expected topic "echoes" (trajectory 0) (resolved topic "/echoes") but no publisher is currently active.
[ WARN] [1602409274.787323572]: W1011 17:41:14.000000 31371 node.cc:857] Expected topic "imu" (trajectory 0) (resolved topic "/imu") but no publisher is currently active.
[ WARN] [1602409274.787405828]: W1011 17:41:14.000000 31371 node.cc:866] Currently available topics are: /constraint_list,/submap_list,/scan_matched_points2,/rosout,/tf,/rosout_agg,/trajectory_node_list,/landmark_poses_list,
[ WARN] [1602409286.879025720]: W1011 17:41:26.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409287.080094124]: W1011 17:41:27.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409287.282269438]: W1011 17:41:27.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409287.484532516]: W1011 17:41:27.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409287.686650920]: W1011 17:41:27.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409287.889005220]: W1011 17:41:27.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 
[ WARN] [1602409288.090032656]: W1011 17:41:28.000000 31371 tf_bridge.cc:52] "base_link" passed to lookupTransform argument target_frame does not exist. 

I cannot get any output because of those warnings. Can you help me?
Thank you!

**Comment by ojura** [comment]
Hi, you should open this issue in https://github.com/cartographer-project/cartographer.

**Comment by yuan608** [comment]
Oh, sorry, I am new on GitHub. I just download your cartographer_superbuild and met this issue, This is the reason I opened this issue here. I have solved this issue and maybe you can delete it if it is under a wrong page. Here is my solution.

The warn happened because cartographer_ros subscribe topic echoes, however, the bag publish topic horizontal_laser_2d and topic vertical_laser_2d. So the data from bag cannot transfer to cartographer_node correctly. 
![Screenshot from 2020-10-15 15-30-02](https://user-images.githubusercontent.com/70429489/96091198-dd75d800-0efb-11eb-8358-72aa689ba465.png)
In order to deal with this problem. I changed two launch files. I deleted the node cartographer_node in backpack_2d.launch and added  order remap from="horizontal_laser_2d" to="echoes" /
  /node in demo_backpack_2d.launch.

backpack_2d.launch,
![Screenshot from 2020-10-15 15-40-00](https://user-images.githubusercontent.com/70429489/96091956-caafd300-0efc-11eb-927f-739954af60bd.png)

demo_backpack_2d.launch,
![Screenshot from 2020-10-15 15-40-09](https://user-images.githubusercontent.com/70429489/96092000-d7342b80-0efc-11eb-9aca-1ff177ee58db.png)

Then I ran cartographer_node in Clion and started another nodes by the launch file. Amazing, I got correct output.
![Screenshot from 2020-10-15 15-49-44](https://user-images.githubusercontent.com/70429489/96092921-13b45700-0efe-11eb-82c0-4a46763f5eb4.png)
